### PR TITLE
Add and use HashCode polyfill

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR polyfills the HashCode implementation using the same logic as MathF.

### CODE REVIEW

**Comment by iamcarbon** [comment]
PING @JimBobSquarePants

**Comment by iamcarbon** [comment]
Oh, I'm dumb. Fix coming!

**Comment by iamcarbon** [comment]
And fixed!

**Comment by iamcarbon** [comment]
@JimBobSquarePants OK, I think all is well now. Made a super dumb mistake. :)

**Comment by iamcarbon** [comment]
@JimBobSquarePants Do we even need the TypeForwardedFor attributes?

**Comment by JimBobSquarePants** [comment]
>Do we even need the TypeForwardedFor attributes?

As far as I'm aware they are an absolute requirement to prevent ambiguous reference exceptions.

**Comment by iamcarbon** [comment]
Once this lands on MyGET, I'll do a pass on ImageSharp to get everything updated.

**Pull request merged**
