### PR TITLE
Use MathF for .Net Core 2.0

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
This PR adds a new .NET Core 2.0 build target so we can take advantage of the new optimized `MathF` methods available there. In order to do so I had to move our `MathF` class to the `System` namespace

I've also removed unused methods and moved the Degree/Radian conversions to a new `MathFExtensions` class as they cannot stay within the `System.MathF` class as it would cause ambiguous references.

We'll have to update our other libraries to use the new namespace.

### CODE REVIEW

**Comment by tocsoft** [comment]
i'm pretty sure your PR is not going to work as expected, when you compile you actually link to a method on a class withing an explicit assembly, you can't remove the class in one version without having the whole chain recompiled explicitly again netstandard2.0. 

we instead have to add a proxyclass that forwards all the calls over to `System.MathF` 

instead we should have  2 versions of `SixLabors.MathF` one that provides an implementation for `! NETSTANARD20` and a second that has aggresive inlining that just proxies to Sytstem.MathF

**Comment by JimBobSquarePants** [comment]
I dunno, I just copied what they've done here.

https://github.com/dotnet/corefx/blob/master/src/Common/src/System/MathF.netstandard.cs

**Comment by tocsoft** [comment]
the problem will happen when Imagesharp being compiled for 1.1 will use the version that included System.MathF and will expect the type to live in SixLabors.Core then when a user on 2.0 uses image sharp they will pull in the version with the type missing then Imagesharp will try and use MathF inside the Core assembly which will be missing thus breaking things.

I think what we need to use is `System.Runtime.CompilerServices.TypeForwardedToAttribute` when compiled against 2.0  https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime

**Comment by JimBobSquarePants** [comment]
I don't get it. If they are targeting 2.0 they won't get the 1.1 version. Wouldn't we create separate targets for Core 2.0 in ImageSharp also?

**Comment by tocsoft** [comment]
I don't have the intention of trying to add new targets this late, because its not just imagesharp, its all the projects that might be effected. 

I can't be have too many moving pieces this late in trying to release, its just another risk for something to go wrong.

As we've already been delayed a day i'm feeling we should park this today to get it sorted for a beta2 which we can release quickly after beta1.

**Comment by antonfirsov** [comment]
@tocsoft totally agree. I'm also concerned we may introduce a future compatibility issue with this change. Also came to conclusion that we may play with type forwarding somehow, but just can't figure out all the details now. Let's do this after beta1!

**Comment by JimBobSquarePants** [comment]
Happy to wait then I guess; Pretty sure I can put it together after. Adding the 2.0 target  to the other libraries is easy enough though, you end up only having to add `System.Memory` as an additional reference.

**Comment by terrajobst** [comment]
Having stubs for our APIs is fine, but you don't want to make your copy of `System.MathF` public. Practically speaking, it doesn't matter as nobody can expose your copy of `System.MathF` in APIs (because it's a static class and the compiler won't let you) but it might confuse customers when they happen to have a reference to also get what amounts to BCL APIs.

In general, don't assume that if you multi-target in a NuGet package that 2.0 customers don't get the 1.1 version. Folks compiling against your 1.1 copy can be consumed from a project targeting 2.0, so you want to make sure the API surface you expose in your 1.1 assembly will unify with all the types you ship in your 2.0 assembly.

Does that make sense?

**Comment by JimBobSquarePants** [comment]
Thanks @terrajobst 

Yeah, I think that makes sense. That's why I've kept it internal for our use only.
https://github.com/SixLabors/Core/pull/7/files#diff-db27b6cf3ee5de040b2a9455aa028df0L13

The idea is that each of our consuming libraries (Shapes, Fonts, ImageSharp) which can access the internal stub will have framework targets for 1.1, and 2.0 (Some have 1.3, 1.4 also)

That, in my mind, will ensure that our internal references get the new BCL class with the targeted 2.0 build and consumers who have no access to the internal stub are not exposed to any changes other than the increased performance whatever they compile against.  

That's correct yeah?

**Comment by terrajobst** [comment]
> That's why I've kept it internal for our use only.

Don't drink and review PRs. I could have sworn to have seen a public type. Never mind then :-)

> The idea is that each of our consuming libraries (Shapes, Fonts, ImageSharp) which can access the internal stub will have framework targets for 1.1, and 2.0 (Some have 1.3, 1.4 also)
>
> That, in my mind, will ensure that our internal references get the new BCL class with the targeted 2.0 build and consumers who have no access to the internal stub are not exposed to any changes other than the increased performance whatever they compile against.

In .NET, type references include the declaring assembly. If two assemblies both declare `System.MathF` the CLR will not consider them the same unless one is type forwarded to the other. If the consuming libraries are compiled against your stub, they will still get the stubbed version on .NET Core 2.0. However, you could add a .NET Core 2.0 specific version to SixLabors that type forwards System.MathF. This way, the behavior would be as you described.

Sketch:


```C#
#if NETCOREAPP2_0

[assembly: TypeForwardedTo(typeof(System.MathF))]

#elif
  
 namespace System
 {
	internal static class MathF
	{
		// The methods you want to stub
	}
}

#endif
```
However, if you do that you have to be careful that your stubbed version of `System.MathF` is a pure subset of ours because on .NET Core 2.0 you will replace your copy with the one we ship, so you can't add your own helper methods to that type.

**Comment by JimBobSquarePants** [comment]
@terrajobst Ok, I've updated my class to follow your sketch. Hoping I've got it this time. 🤞 

https://github.com/SixLabors/Core/blob/02ba06c183911f312f4125dfeb37ec05849d6289/src/SixLabors.Core/MathF.cs

**Comment by terrajobst** [comment]
Good luck! Versioning an binary compat is hard :-) I'd test it before merging :-)

**Comment by JimBobSquarePants** [comment]
@terrajobst Thanks for your help!

**Comment by JimBobSquarePants** [comment]
@tocsoft Yeah I'll give you that one 👍

**Pull request merged**
